Day37 Router 코드리뷰 요청드립니다.
nlutter-study/nlutter-study-2nd pull request #23
Opened 2023-12-19 15:13 UTC by 0hhanum

Day37 과제 코드리뷰 요청드립니다.

80661d35d88b0ec3318c108c011da6d5b195bc64 부터 과제입니다.

`goRouter`의 `context.go()` 메서드 사용 시 라우트 이동 마다 `ThreadMainNav` 위젯이 `currentTab`을 받기 때문에  새로 렌더링되어 `createState`가 재실행 될 것이라 생각했는데 그렇지 않더라구요. `key`가 동일하기 때문에 변경사항만 처리되는 걸까요? 

탭을 변경해도 스크린의 상태가 유지(OffStage 사용한 것처럼) 되는 이유도 같은 이유일 것 같은데 궁금합니다 .!

추가로 PR 올리려고 푸시 후 테스트 통과 못해 수정해 다시 푸시했는데, 일반적으로 이런 경우 현업에서 저처럼 fix 내역을 커밋으로 그대로 남겨두는지도 궁금합니다.. 이전 내역에 스쿼시하고 충돌 수정 후에 PR을 올리나요?

감사합니다 !

2023-12-19 23:26 UTC, devgony reviewed
잘 정리해서 올려주셔서 감사합니다.

일단 commit 관련해서 답변을 먼저 드리자면 실수가 있었거나 액션에 대한 내용을 수정하기 위해 fix 했던 내용까지 모두 그대로 남겨놓는게 reviewer 입장에서 용이합니다.
물론 commit 이 너무 많아지게되면 rebase 를 통해 일부 커밋들은 모듈단위로 묶어주시면 도움이 되는 경우도 있으나 굳이 그러시지 않아도 되는게 
보통은 merge 할때 squash merge를 해서 PR 1 개당 1 개의 commit 이 되도록 합니다.
그렇게 하면 main에서 (현재의 경우 각 githubID branch) 는 하나의 commit 이지만 어차피 PR 번호를 눌러서 이동하게되면 개발 하셨을때의 세부 commit 내역들도 그대로 볼 수 있게 되니까요 😄

2023-12-24 11:11 UTC, devgony requested changes

2023-12-24 11:11 UTC, devgony commented on lib/router.dart
> +}
MainNavTab 에 필요한 각 경우들을 enum 으로 잘 정의 해주셨습니다.
여기에 추가로 미리 멤버 변수들을 선언 해두면 로직 구현 시 코드가 깔끔해지고 구현에만 집중할 수 있을 것 같습니다.

BottomAppBar 를 위해 post 도 포함했습니다.
label 은 name 으로 대체 가능하여 제거하였습니다.

```dart
enum MainNavTab {
  home(
    screen: ThreadHomeScreen(),
    icon: FontAwesomeIcons.house,
  ),
  search(
    screen: ThreadSearchScreen(),
    icon: FontAwesomeIcons.magnifyingGlass,
  ),
  post(
    screen: ThreadPostScreen(),
    icon: FontAwesomeIcons.penToSquare,
  ),
  activity(
    screen: ThreadActivityScreen(),
    icon: FontAwesomeIcons.heart,
  ),
  profile(
    screen: ThreadProfileScreen(),
    icon: FontAwesomeIcons.person,
  );

  const MainNavTab({
    required this.screen,
    required this.icon,
  });
  final Widget screen;
  final IconData icon;
}
```

2023-12-24 11:11 UTC, devgony commented on lib/router.dart
> +}
GoRoute 가 Nested 하게 정의되면 subroute를 알아서 설계 해주므로 사실 추가적인 설계는 큰 의미가 없을 것 같긴하지만.. 의미상의 명확한 구분을 위해서는 아래처럼 `class Settings` 로 분리해 볼 수는 있을 것 같습니다.

subroute가 없는 경우에는 enum 으로 만드셔도 상관 없을 것으로 보입니다.

```dart
class Routes {
  static const home = "/";
  static const mainNav = "/:tab";
  static final settings = Settings();
}

class Settings {
  final base = "/settings";
  final privacy = "privacy";
  final sampleSubroute = "sample-subroute";
}
```

2023-12-24 11:11 UTC, devgony commented on lib/router.dart
> +        }
아래와 같이 string 으로부터 enum 을 가져오는 방법도 있습니다.
잘못된 string이 들어올 수 있으므로 아래 예시는 home 으로 보내지만 404 관련 페이지가 하나 있으면 더 좋을 듯 합니다.

```dart
final tab = MainNavTab.values.firstWhere(
  (v) => v.name == tabString,
  orElse: () => MainNavTab.home, // or 404 page
);
```

2023-12-24 11:11 UTC, devgony commented on lib/navs/thread_main_nav.dart
>    ];
enum.values 를 활용하여 간편하게 _screenList 생성이 가능합니다.

```dart
final _screenList = MainNavTab.values.toList();
```

2023-12-24 11:11 UTC, devgony commented on lib/navs/thread_main_nav.dart
>    State<ThreadMainNav> createState() => _MainNavState();
> goRouter의 context.go() 메서드 사용 시 라우트 이동 마다 ThreadMainNav 위젯이 currentTab을 받기 때문에 새로 렌더링되어 createState가 재실행 될 것이라 생각했는데 그렇지 않더라구요. key가 동일하기 때문에 변경사항만 처리되는 걸까요?

createState() 는 StatefulWidget 이 최초에 만들어질 때 1회 만 호출되고 그 이후에는 state가 변경되어도 호출되지 않습니다.
아마 state 가 변경될 때마다 build() 가 재수행 되는 것과 혼동되실 수 있었을 것 같습니다.

2023-12-24 11:11 UTC, devgony commented on lib/navs/thread_main_nav.dart
> +        index: _getTabIndex(), // post 건너뛰기
> 탭을 변경해도 스크린의 상태가 유지(OffStage 사용한 것처럼) 되는 이유도 같은 이유일 것 같은데 궁금합니다 .!
 
강의에서처럼 `late final int _selectedIndex = _tabs.indexOf(widget.tab);` 와 같은 방식으로 index 를 넣어주었다면 아마 @0hhanum 님께서도 setState를 해줘야만 탭 변경시마다 화면이 변경 되셨을 테지만 지금은 build 할 때마다 _getTabIndex() 를 실행하기 때문에 문제없이 화면이 변경되고 있습니다.

바꿔 말하면 탭 변경 시마다 build() 가 일어나고 있고 심지어 다른 state 가 변경되어도 해당 함수는 재실행이 된 다는 의미이기 때문에 근원이 되는 widget.currentTab 으로부터 바로 index 값을 가져오는게 더 좋을 것 같습니다.

```suggestion
        index: widget.currentTab.index,
```

2023-12-24 11:11 UTC, devgony commented on lib/navs/thread_main_nav.dart
>          ],
iterator method 를 통해 표현 해볼 수 있습니다.

```dart
        children: _screenList.map((screen) => screen.screen).toList(),
```

2023-12-24 11:11 UTC, devgony commented on lib/navs/thread_main_nav.dart
>          ],
class 내부 method 로 로직을 분리하면 map 과 function reference 으로 좀더 간결하게 표현이 가능합니다.

```dart
children: _screenList.map(_buildThreadNavTab).toList(),
```

```dart
class _MainNavState extends State<ThreadMainNav> {
...
  ThreadNavTab _buildThreadNavTab(MainNavTab screen) {
    return ThreadNavTab(
      isSelected: widget.currentTab == screen,
      icon: screen.icon,
      label: screen.name,
      onTap: (screen == MainNavTab.post)
          ? _onPost
          : () => _setSelectedIndex(screen),
    );
  }
...
```

2024-01-06 08:03 UTC, 0hhanum commented
360d94001e26f9fdd44245abadc91193a9c23a42

리뷰 내용 반영 완료했습니다 !
`_screenList`는 탭 enum이 `screen`, `icon` 을 멤버로 가지게 되면서 불필요해져 삭제했습니다.

2024-01-06 08:31 UTC, devgony reviewed
추가로, router 의 경우 이런 workaround 를 써볼수도 있을것 같습니다.

```dart
final router = GoRouter(
  initialLocation: "/${const MenuScreen()}",
  routes: [
    _getRoute(const MenuScreen()),
    _getRoute(const Day57ImplicitAnimations()),
    _getRoute(const Day59ExplicitAnimations()),
    _getRoute(const Day61CustomPainter()),
    _getRoute(const Day64FlashcardsApp())
  ],
);

GoRoute _getRoute(Widget screen) => GoRoute(
      name: screen.toString(),
      builder: (context, state) => screen,
      path: "/$screen",
    );
```

2024-01-06 08:31 UTC, devgony commented on lib/router.dart
> +      path: Routes.settings,
현재 `/` 와 `/home` 모두 같은 화면을 바라보고 있어서 중복되는 route 를 두는 것 보다는 아래와 같이 설정하는 것이 더 좋아보입니다.

```suggestion
  initialLocation: "/${MainNavTab.home.name}",
  routes: [
    GoRoute(
        path: Routes.settings,
```

2024-01-06 08:50 UTC, devgony approved these changes
고생 많으셨습니다!
바로 다음 PR 이어서 리뷰 진행 하겠습니다.

2024-01-06 08:50 UTC, merged