Deviflix original
nlutter-study/nlutter-study-2nd pull request #24
Opened 2023-12-20 13:51 UTC by asuracoder91

2023-12-21 15:05 UTC, devgony requested changes

2023-12-21 15:05 UTC, devgony commented on lib/features/home/screens/home_screen.dart
> +        ),
메인 화면의 AppBar가 너무 기므로 적절한 이름의 위젯으로 한번 분리 해주시면 좋을 것 같습니다.

2023-12-21 15:05 UTC, devgony commented on lib/core/api/api_service.dart
> +  }
1. 버그를 발생 시킬 수 있는 String 이 아니라 3가지의 경우를 제한하는 enum MovieOrder (다른 코멘트에 코드 남기겠습니다)  를 파라미터로 받을 수 있습니다.

2. async 작업의 경우 예기치 못한 에러가 발생할 수 있으므로 전체를 try-catch 로 감싸주는것이 좋습니다.

3. statusCode 가 200 이 아닌경우를 early return 하여 indentation 을 줄일 수 있습니다.

4. movieInstances 와 같이 빈 array 를 만들고 add 하는 mutation 은 지양하는 것이 좋습니다. 최대한 final 키워드를 써주시는것이 좋고, iterator 의 함수형 메서드를 활용하여 구현하면 코드의 길이가 짧아질 뿐만아니라 pure function만으로 동작하기 때문에 반복해서 수행해도 동일한 결과값을 보장하게 되고 이는 테스트 시에도 용이하게 됩니다.

```dart
static Future<List<MovieModel>> getMovies(MovieOrder movieOrder) async {
  try {
    final url = Uri.parse('$baseUrl/${movieOrder.value}');
    final response = await http.get(url);

    if (response.statusCode != 200) {
      throw Error();
    }

    return jsonDecode(utf8.decode(response.bodyBytes))['results']
        .map<MovieModel>((movie) => MovieModel.fromJson(movie))
        .toList();
  } catch (e) {
    throw Exception("An error occurred while loading the movies");
  }
}
```

2023-12-21 15:05 UTC, devgony commented on lib/features/home/screens/home_screen.dart
> +                  builder: (context, snapshot) {
에러가 발생하는 경우에 대해 스낵바 메시지를 추가하면 더 좋을 것 같습니다.
```dart
if (snapshot.hasError) {
  ScaffoldMessenger.of(context).showSnackBar(
    const SnackBar(
      content: Text('An error occurred while loading the movies'),
    ),
  );
}
```

2023-12-21 15:05 UTC, devgony commented on lib/features/home/screens/home_screen.dart
> +
enum MovieOrder 를 정의 하였습니다. (사실 너무 길어져서 별도 파일에 정의해주시면 더 좋을 듯 합니다.)

각 enum variant 에 따라 필요한 속성들을 미리 넣어두었으며 특히 build 메서드는 MovieList (하단 리뷰 참조) 를 호출하는데 nowPlaying 의 경우 컨테이너 배경을 한번 더 감싸주는 처리를 합니다.

```dart
enum MovieOrder {
  popular(
    value: "popular",
    imagePath: '',
    height: 371,
  ),
  nowPlaying(
    value: "now-playing",
    title: 'Now On Cinema',
    imagePath: 'assets/images/flame.png',
    left: 15,
    width: 16,
    height: 140,
    crossAxisAlignment: CrossAxisAlignment.start,
  ),
  upcoming(
    value: "coming-soon",
    title: 'Coming Soon',
    imagePath: "assets/images/ddoza.png",
    left: 10,
    width: 22,
    height: 170,
    crossAxisAlignment: CrossAxisAlignment.center,
  );

  const MovieOrder({
    required this.value,
    this.title = '',
    required this.imagePath,
    this.left = 0,
    this.width,
    required this.height,
    this.crossAxisAlignment = CrossAxisAlignment.start,
  });
  final String value;
  final String title;
  final String imagePath;
  final double left;
  final double? width;
  final double height;
  final CrossAxisAlignment crossAxisAlignment;

  Widget build() {
    final child = MovieList(movieOrder: this);
    return switch (this) {
      MovieOrder.nowPlaying => Container(
          decoration: const BoxDecoration(
            color: Color(0xFF1D1D1D),
            border: Border.symmetric(
              horizontal: BorderSide(
                width: 8,
                color: Color(0xFF262626),
              ),
            ),
          ),
          height: 210,
          child: child,
        ),
      _ => child,
    };
  }
}
```

2023-12-21 15:05 UTC, devgony commented on lib/features/home/screens/home_screen.dart
> +                        ),
SizedBox 로 감싸여있는 FutureBuilder 가 공통 부분임을 착안하여 MovieList 위젯을 추출하였습니다.

refactoring 중 title 도 합칠 수 있는것을 확인 하였고 MovieTitle (하단 리뷰 참조) 과 마진으로 쓰이는 SizedBox 도 경우에 따라 추가 하게 되었습니다.

```dart
class MovieList extends StatelessWidget {
  const MovieList({super.key, required this.movieOrder});
  final MovieOrder movieOrder;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        switch (movieOrder) {
          MovieOrder.popular => const SizedBox.shrink(),
          MovieOrder.nowPlaying => const SizedBox(height: 10),
          MovieOrder.upcoming => const SizedBox(height: 14),
        },
        MoiveTitle(movieOrder: movieOrder),
        if (movieOrder == MovieOrder.nowPlaying) const SizedBox(height: 10),
        SizedBox(
          height: movieOrder.height,
          child: FutureBuilder(
            future: ApiService.getMovies(movieOrder),
            builder: (context, snapshot) {
              if (snapshot.hasError) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('An error occurred while loading the movies'),
                  ),
                );
              }
              if (snapshot.hasData) {
                return switch (movieOrder) {
                  MovieOrder.popular => PopularMoviesView(snapshot: snapshot),
                  MovieOrder.nowPlaying => getNowOnCinema(snapshot, 136, 96),
                  MovieOrder.upcoming => getComingSoon(snapshot, 86, 131),
                };
              }
              return const Center(
                child: CircularProgressIndicator(),
              );
            },
          ),
        ),
      ],
    );
  }
}
```

2023-12-21 15:05 UTC, devgony commented on lib/features/home/screens/home_screen.dart
> +              ),
Padding 안의 내용들이 거의 유사한 점에 착안하여 MovieTitle 위젯을 추출하였습니다.
MovieOrder.Popular 의 경우 해당 부분이 없으므로 MovieTitle 은 처음부터 switch expression 으로 시작하여 분기를 나누게 됩니다.

```dart
class MoiveTitle extends StatelessWidget {
  const MoiveTitle({super.key, required this.movieOrder});
  final MovieOrder movieOrder;

  @override
  Widget build(BuildContext context) => switch (movieOrder) {
        MovieOrder.popular => const SizedBox.shrink(),
        _ => Padding(
            padding: EdgeInsets.only(
              left: movieOrder.left,
            ),
            child: Row(
              crossAxisAlignment: movieOrder.crossAxisAlignment,
              children: [
                Image.asset(
                  movieOrder.imagePath,
                  width: movieOrder.width,
                ),
                const Gap(6),
                switch (movieOrder) {
                  MovieOrder.popular => throw Error(),
                  MovieOrder.nowPlaying => GradientText(
                      movieOrder.title,
                      style: commonTextStyle,
                      colors: const [
                        Color(0xFFBC0404),
                        Color(0xFFFAFF00),
                      ],
                      gradientDirection: GradientDirection.btt,
                    ),
                  MovieOrder.upcoming => Text(
                      movieOrder.title,
                      style: commonTextStyle,
                    ),
                },
              ],
            ),
          )
      };
}

const commonTextStyle = TextStyle(
  fontSize: 20,
  fontWeight: FontWeight.w600,
  letterSpacing: -0.5,
);

```

2023-12-21 15:05 UTC, devgony commented on lib/features/home/screens/home_screen.dart
> +}
HomeScreen.body 의 최종 모습입니다.
MovieOrder.values 를 통해 enum 의 모든 경우의 수를 List 로 만든 후에 iterator method 로 처리 하였습니다.

```dart
body: SingleChildScrollView(
  child: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      const SizedBox(height: 50),
      ...MovieOrder.values
          .map((movieOrder) => movieOrder.build())
          .toList(),
      const SizedBox(height: 40),
    ],
  ),
),
```

2023-12-21 15:05 UTC, devgony commented on lib/features/home/screens/home_screen.dart
> +                  ),
위 아래에 divider 를 넣는 로직으로 보여서 중간 Container 에 horizontal border 를 넣어 동일하게 구현 해볼수도 있을 것 같습니다.

최종 결과물에서 해당 코드는 MovieOrder.build 메서드 안으로 이동됩니다.

```dart
border: Border.symmetric(
  horizontal: BorderSide(
    width: 8,
    color: Color(0xFF262626),
  ),
),
```

2023-12-21 15:10 UTC, devgony requested changes

2023-12-21 15:10 UTC, devgony commented on pubspec.yaml
> +    sdk: ">=2.19.6 <3.0.0"
Dart 3 sdk 를 사용해주셔야 위 리뷰에 있는 switch expression 과 같은 최신 문법 사용이 가능합니다. 새로운 기능 공부를 위해 변경 해보시면 좋을 것 같습니다!
```suggestion
    sdk: "3.2.3"
```

2023-12-24 15:23 UTC, asuracoder91 commented on pubspec.yaml
> +    sdk: ">=2.19.6 <3.0.0"
sdk 버전은 신경안쓰고 fvm만 쓸데없이 매번 업데이트 시켰었군요. 
어쩐지 Dart SDK관련 warning이 뜨더라니
`sdk: ">=3.2.3 <4.0.0"`요렇게 수정했습니다

2023-12-29 14:16 UTC, asuracoder91 commented on lib/features/home/screens/home_screen.dart
> +        ),
MainAppBar Widget을 만들어 파일을 분리하였습니다.
복제한 폴더에서 엉뚱하게 커밋 & 푸시하는 바람에 지저분한 커밋들이 많이 생겨버렸네요 ㅠㅠ
링크(https://github.com/nlutter-study/nlutter-study-2nd/pull/24/commits/d8d88a4c3814e98ff572511694ef538edef8be5d)

2023-12-29 14:45 UTC, asuracoder91 commented on lib/core/api/api_service.dart
> +  }
enum이 단순히 새로운 Type을 생성하는 거라고 생각했는데 엄청 많은 것들을 집어넣을 수 있었네요
4번은 주의하겠습니다
enum을 포함해서 정리해주신 코드를 한 번에 커밋했습니다 (https://github.com/nlutter-study/nlutter-study-2nd/pull/24/commits/e6822028ec12d709e45935cf8b9219c8cfb93ca9)

2023-12-29 14:48 UTC, asuracoder91 commented on lib/features/home/screens/home_screen.dart
> +
enum 안에 Constructor와 build위젯을 넣을 수 있을 줄은 몰랐네요

2023-12-29 14:51 UTC, asuracoder91 commented on lib/features/home/screens/home_screen.dart
> +                        ),
굳이 이렇게 더 코드를 길게 만들면서까지 위젯 추출이 필요할까하는 생각을 했는데 마지막에 HomeScreen 위젯이 한번에 줄이는 매직을 보고 이마를 탁 치게 되었습니다. switch 문은 Rust의 match를 쏙 빼닮았네요

2024-01-06 07:21 UTC, devgony commented on lib/features/home/screens/home_screen.dart
> +                        ),
사실 이렇게 개발하는 방식이 더 군더더기를 만드는 경우도 있겠으나 이번 코드리뷰에서는 최대한 Dart3 의 문법을 활용해서 적용해보는 것을 목표로 하고 리뷰를 달았습니다. 

Dart3 에서 생긴 또하나의 문법은 sealed class 인데 이것도 switch 를 동일하게 쓸 수 있지만 각 경우들이 각각 다른 필드를 가질 수 있어서 사실 지금의 환경에서 더 유용할 수도 있습니다. 아래는 참고용으로만 봐주시고 sealed class 는 다음번 과제에서 적용 해보아요!
```dart
import 'package:deviflix/features/home/screens/widgets/movie_list.dart';
import 'package:flutter/material.dart';

sealed class MovieOrder {
  final String value;
  final double height;
  MovieOrder._({
    required this.value,
    required this.height,
  });

  static final popular = Popular();

  static final nowPlaying = NowPlaying();

  static final upcoming = Upcoming();

  static final values = [
    MovieOrder.popular,
    MovieOrder.nowPlaying,
    MovieOrder.upcoming,
  ];

  Widget build() {
    final child = MovieList(movieOrder: this);
    return switch (this) {
      NowPlaying() => Container(
          decoration: const BoxDecoration(
            color: Color(0xFF1D1D1D),
            border: Border.symmetric(
              horizontal: BorderSide(
                width: 8,
                color: Color(0xFF262626),
              ),
            ),
          ),
          height: 210,
          child: child,
        ),
      _ => child,
    };
  }
}

class Popular extends MovieOrder {
  Popular() : super._(value: "popular", height: 371);
}

class NowPlaying extends MovieOrder {
  NowPlaying() : super._(value: "now-playing", height: 140);

  final title = 'Now On Cinema';
  final String imagePath = "assets/images/flame.png";
  final double left = 15;
  final double width = 16;
  final CrossAxisAlignment crossAxisAlignment = CrossAxisAlignment.start;
}

class Upcoming extends MovieOrder {
  Upcoming() : super._(value: "coming-soon", height: 170);

  final title = 'Coming Soon';
  final String imagePath = "assets/images/ddoza.png";
  final double left = 10;
  final double width = 22;
  final CrossAxisAlignment crossAxisAlignment = CrossAxisAlignment.center;
}
```

2024-01-06 07:40 UTC, devgony approved these changes
모두 잘 반영 해주셨군요! 고생 많으셨습니다!
이제 다음 과제에 대해서도 새로운 PR 로 올려주시면 됩니다!

2024-01-06 07:40 UTC, merged